on:
  pull_request_review:
    types:
      - submitted
jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: review
        uses: buildsville/review-summary@v1
        id: summary
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: print review summary
        run: |
          echo "APPROVE: ${{ steps.summary.outputs.approved }}"
          echo "REQUEST_CHANGES: ${{ steps.summary.outputs.changes_requested }}"
          echo "COMMENT: ${{ steps.summary.outputs.commented }}"
          echo "PENDING: ${{ steps.summary.outputs.pending }}"
      - name: print if more than 2 approve
        if: steps.summary.outputs.approved > 2
        run: |
          echo "Got more than 2 approvals"

      - name: remove 'Ready for review' label when approved
        uses: actions-ecosystem/action-remove-labels@v1
        if: steps.summary.outputs.approved > 0 && steps.summary.outputs.changes_requested == 0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "2. Ready for review"
      - name: add 'Passed code review' label when approved
        uses: actions-ecosystem/action-add-labels@v1
        if: steps.summary.outputs.approved > 0 && steps.summary.outputs.changes_requested == 0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "4. Passed code review"
